version: '2'

services:
    nginx:
        image: nginx:1.15.8
        ports:
            - "5555:8080"
        volumes:
            - ./nginx_reverse_proxy.conf:/etc/nginx/conf.d/default.conf:ro
            - ./store/static/files:/static:ro
        links:
            - gunicorn
            - node

    gunicorn:
        container_name: gunicorn
        build: ./py

    node:
        container_name: node
        build: ./js
